import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ExternalLink } from "lucide-react";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { ContentPanel, ContentPanels } from "@/components/content-panels";
import { getProductPath, products } from "@/lib/data";
import { getPublishedNewsBySlug } from "@/lib/news/store";
import { splitArticleSections } from "@/lib/article-sections";
import { absoluteUrl, createPageMetadata } from "@/lib/seo";

export const dynamic = "force-dynamic";
type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props) { const { slug } = await params; const article = await getPublishedNewsBySlug(slug); return article ? createPageMetadata({ title: article.seoTitle, description: article.seoDescription, path: `/news/${article.slug}`, keywords: [article.primaryKeyword || "aerogel news", ...article.secondaryKeywords], index: article.indexable }) : createPageMetadata({ title: "News Brief Not Found | Cowin Materials", description: "The requested Cowin Materials news brief was not found.", path: "/news", index: false }); }
export default async function NewsDetailPage({ params }: Props) {
  const { slug } = await params; const article = await getPublishedNewsBySlug(slug); if (!article) notFound();
  const sections = splitArticleSections(article.contentHtml);
  const isTechnicalNote = article.originType === "first_party_technical_note";
  const jsonLd = { "@context": "https://schema.org", "@type": isTechnicalNote ? "Article" : "NewsArticle", headline: article.title, description: article.seoDescription, image: [article.image.url], datePublished: article.publishedAt, dateModified: article.updatedAt, author: { "@type": "Organization", name: article.authorName }, publisher: { "@type": "Organization", name: "Cowin Materials" }, mainEntityOfPage: absoluteUrl(`/news/${article.slug}`), ...(isTechnicalNote ? {} : { isBasedOn: { "@type": "CreativeWork", name: article.source.title, url: article.source.url, publisher: article.source.publisher, datePublished: article.source.publishedAt } }) };
  const breadcrumb = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: absoluteUrl("/") }, { "@type": "ListItem", position: 2, name: "News", item: absoluteUrl("/news") }, { "@type": "ListItem", position: 3, name: article.title, item: absoluteUrl(`/news/${article.slug}`) }] };
  return <><Header /><main><article className="article-layout"><Link className="back-link" href="/news"><ArrowLeft size={16} />Back to news</Link><header className="article-header"><span className="eyebrow">{article.category}</span><h1>{article.title}</h1><p>{article.excerpt}</p><div className="news-meta"><span>{isTechnicalNote ? "Cowin Materials Technical Note" : article.source.publisher}</span><span>{new Intl.DateTimeFormat("en", { dateStyle: "long" }).format(new Date(article.publishedAt))}</span></div></header><figure className="article-cover"><Image src={article.image.url} alt={article.image.alt} width={1160} height={640} priority /><figcaption>Editorial illustration for technical context. See the source scope and related product area below.</figcaption></figure><ContentPanels label="News brief sections">{sections.map((section) => <ContentPanel id={section.id} label={section.label} key={section.id}><h2 className="content-panel-title">{section.label}</h2><div className="article-body" dangerouslySetInnerHTML={{ __html: section.html }} /></ContentPanel>)}<ContentPanel id="related-products" label="Related products"><section className="article-related"><h2>Related Cowin Materials product areas</h2><div className="related-news-products">{article.relatedProducts.map((product) => <Link href={getProductPath(products.find((item) => item.slug === product.slug) || product)} key={product.slug}><strong>{product.name}</strong><span>{product.relationshipReason}</span></Link>)}</div></section></ContentPanel><ContentPanel id="source" label={isTechnicalNote ? "Evidence record" : "Source record"}><section className="source-box"><h2>{isTechnicalNote ? "Evidence record" : "Source record"}</h2><dl>{isTechnicalNote ? <><div><dt>Evidence source</dt><dd>{article.technicalSource?.label || article.source.title}</dd></div>{article.technicalSource?.locator ? <div><dt>Source locator</dt><dd>{article.technicalSource.locator}</dd></div> : null}{article.technicalSource?.reportNumber ? <div><dt>Report number</dt><dd>{article.technicalSource.reportNumber}</dd></div> : null}<div><dt>Publication scope</dt><dd>Source-recorded technical data with stated conditions and limits; not a project qualification or certificate.</dd></div></> : <><div><dt>Original source</dt><dd><a href={article.source.url} target="_blank" rel="nofollow noopener">{article.source.title}<ExternalLink size={14} /></a></dd></div><div><dt>Source published</dt><dd>{new Date(article.source.publishedAt).toISOString()}</dd></div></>}<div><dt>Published by Cowin Materials</dt><dd>{new Date(article.publishedAt).toISOString()}</dd></div></dl></section></ContentPanel></ContentPanels></article><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} /></main><Footer /></>;
}
